/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    LoginSuccessTransition: typeof import('./components/auth/LoginSuccessTransition.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NPagination: typeof import('naive-ui')['NPagination']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
